apiVersion: keystone.openstack.org/v1beta1
kind: KeystoneAPI
metadata:
  name: keystone
spec:
  adminProject: admin
  adminUser: admin
  customServiceConfig: |
    [DEFAULT]
    debug = true
  databaseInstance: openstack
  databaseAccount: keystone
  preserveJobs: false
  region: regionOne
  secret: osp-secret
  resources:
    requests:
      memory: "500Mi"
      cpu: "1.0"
  tls:
    api:
      # secret holding tls.crt and tls.key for the APIs internal k8s service
      internal:
        secretName: cert-keystone-internal-svc
      # secret holding tls.crt and tls.key for the APIs public k8s service
      public:
        secretName: cert-keystone-public-svc
    # secret holding the tls-ca-bundle.pem to be used as a deploymend env CA bundle
    caBundleSecretName: combined-ca-bundle
  oidcFederation:
    keystoneFederationIdentityProviderName: my_federation_provider_name
    oidcCacheType: memcache
    oidcClaimDelimiter: ;
    oidcClaimPrefix: OIDC-
    oidcClientID: my_federation_client_id
    oidcIntrospectionEndpoint: my_federation_introspection_endpoint
    oidcMemCacheServers: ""
    oidcPassClaimsAs: both
    oidcPassUserInfoAs: claims
    oidcProviderMetadataURL: my_federation_provider_metadata_url
    oidcResponseType: id_token
    oidcScope: openid email profile
    remoteIDAttribute: HTTP_OIDC_ISS
