// +build !

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/openstack-k8s-operators/keystone-operator/pkg/apis/keystone/v1.KeystoneApi":       schema_pkg_apis_keystone_v1_KeystoneApi(ref),
		"github.com/openstack-k8s-operators/keystone-operator/pkg/apis/keystone/v1.KeystoneApiSpec":   schema_pkg_apis_keystone_v1_KeystoneApiSpec(ref),
		"github.com/openstack-k8s-operators/keystone-operator/pkg/apis/keystone/v1.KeystoneApiStatus": schema_pkg_apis_keystone_v1_KeystoneApiStatus(ref),
	}
}

func schema_pkg_apis_keystone_v1_KeystoneApi(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KeystoneApi is the Schema for the keystoneapis API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/openstack-k8s-operators/keystone-operator/pkg/apis/keystone/v1.KeystoneApiSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/openstack-k8s-operators/keystone-operator/pkg/apis/keystone/v1.KeystoneApiStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/openstack-k8s-operators/keystone-operator/pkg/apis/keystone/v1.KeystoneApiSpec", "github.com/openstack-k8s-operators/keystone-operator/pkg/apis/keystone/v1.KeystoneApiStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_keystone_v1_KeystoneApiSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KeystoneApiSpec defines the desired state of KeystoneApi",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_keystone_v1_KeystoneApiStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KeystoneApiStatus defines the observed state of KeystoneApi",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
