/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
// Generated by:
//
// operator-sdk create webhook --group keystone --version v1beta1 --kind KeystoneAPI --programmatic-validation --defaulting
//

package v1beta1

import (
	"fmt"
	"net/url"

	rabbitmqv1 "github.com/openstack-k8s-operators/infra-operator/apis/rabbitmq/v1beta1"
	"github.com/openstack-k8s-operators/lib-common/modules/common/service"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/validation/field"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
	common_webhook "github.com/openstack-k8s-operators/lib-common/modules/common/webhook"
)

// KeystoneAPIDefaults -
type KeystoneAPIDefaults struct {
	ContainerImageURL string
	APITimeout        int
}

var keystoneAPIDefaults KeystoneAPIDefaults

// log is for logging in this package.
var keystoneapilog = logf.Log.WithName("keystoneapi-resource")

// SetupKeystoneAPIDefaults - initialize KeystoneAPI spec defaults for use with either internal or external webhooks
func SetupKeystoneAPIDefaults(defaults KeystoneAPIDefaults) {
	keystoneAPIDefaults = defaults

	keystoneapilog.Info("KeystoneAPI defaults initialized", "defaults", defaults)
}

var _ webhook.Defaulter = &KeystoneAPI{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *KeystoneAPI) Default() {
	keystoneapilog.Info("default", "name", r.Name)

	if r.Spec.ContainerImage == "" {
		r.Spec.ContainerImage = keystoneAPIDefaults.ContainerImageURL
	}
	r.Spec.Default()
}

// Default - set defaults for this KeystoneAPI spec
func (spec *KeystoneAPISpec) Default() {
	// no defaults to set yet
	spec.KeystoneAPISpecCore.Default()
}

// Default - set defaults for this KeystoneAPI core spec
// NOTE: only this version is used by OpenStackOperators webhook
func (spec *KeystoneAPISpecCore) Default() {
	if spec.APITimeout == 0 {
		spec.APITimeout = keystoneAPIDefaults.APITimeout
	}
	// Default NotificationsBus if RabbitMqClusterName is specified
	if spec.RabbitMqClusterName != "" {
		if spec.NotificationsBus == nil {
			spec.NotificationsBus = &rabbitmqv1.RabbitMqConfig{}
		}
		rabbitmqv1.DefaultRabbitMqConfig(spec.NotificationsBus, spec.RabbitMqClusterName)
	}
}

var _ webhook.Validator = &KeystoneAPI{}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *KeystoneAPI) ValidateCreate() (admission.Warnings, error) {
	keystoneapilog.Info("validate create", "name", r.Name)

	var allWarns []string
	allErrs := field.ErrorList{}
	basePath := field.NewPath("spec")

	warns, errs := r.Spec.ValidateCreate(basePath, r.Namespace)
	allWarns = append(allWarns, warns...)
	allErrs = append(allErrs, errs...)

	if len(allErrs) != 0 {
		return allWarns, apierrors.NewInvalid(GroupVersion.WithKind("KeystoneAPI").GroupKind(), r.Name, allErrs)
	}

	return allWarns, nil
}

// ValidateCreate - Exported function wrapping non-exported validate functions,
// this function can be called externally to validate an KeystoneAPI spec.
func (spec *KeystoneAPISpec) ValidateCreate(basePath *field.Path, namespace string) ([]string, field.ErrorList) {
	return spec.KeystoneAPISpecCore.ValidateCreate(basePath, namespace)
}

// ValidateCreate validates the KeystoneAPISpecCore spec during creation
func (spec *KeystoneAPISpecCore) ValidateCreate(basePath *field.Path, namespace string) ([]string, field.ErrorList) {
	var allErrs field.ErrorList
	var allWarns []string

	// Validate deprecated fields using reflection-based validation
	warnings, errs := spec.validateDeprecatedFieldsCreate(basePath)
	allWarns = append(allWarns, warnings...)
	allErrs = append(allErrs, errs...)

	// validate the service override key is valid
	allErrs = append(allErrs, service.ValidateRoutedOverrides(basePath.Child("override").Child("service"), spec.Override.Service)...)

	// When a TopologyRef CR is referenced, fail if a different Namespace is
	// referenced because is not supported
	allErrs = append(allErrs, spec.ValidateTopology(basePath, namespace)...)

	// Validate external Keystone API configuration
	allErrs = append(allErrs, spec.ValidateExternalKeystoneAPI(basePath)...)

	return allWarns, allErrs
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *KeystoneAPI) ValidateUpdate(old runtime.Object) (admission.Warnings, error) {
	keystoneapilog.Info("validate update", "name", r.Name)

	oldKeystoneAPI, ok := old.(*KeystoneAPI)
	if !ok || oldKeystoneAPI == nil {
		return nil, apierrors.NewInternalError(fmt.Errorf("unable to convert existing object"))
	}

	var allWarns []string
	allErrs := field.ErrorList{}
	basePath := field.NewPath("spec")

	warns, errs := r.Spec.ValidateUpdate(oldKeystoneAPI.Spec, basePath, r.Namespace)
	allWarns = append(allWarns, warns...)
	allErrs = append(allErrs, errs...)

	if len(allErrs) != 0 {
		return allWarns, apierrors.NewInvalid(GroupVersion.WithKind("KeystoneAPI").GroupKind(), r.Name, allErrs)
	}

	return allWarns, nil
}

// ValidateUpdate - Exported function wrapping non-exported validate functions,
// this function can be called externally to validate an ironic spec.
func (spec *KeystoneAPISpec) ValidateUpdate(old KeystoneAPISpec, basePath *field.Path, namespace string) ([]string, field.ErrorList) {
	return spec.KeystoneAPISpecCore.ValidateUpdate(old.KeystoneAPISpecCore, basePath, namespace)
}

// ValidateUpdate validates the KeystoneAPISpecCore spec during update
func (spec *KeystoneAPISpecCore) ValidateUpdate(old KeystoneAPISpecCore, basePath *field.Path, namespace string) ([]string, field.ErrorList) {
	var allErrs field.ErrorList
	var allWarns []string

	// Validate deprecated fields using centralized validation
	warnings, errs := spec.validateDeprecatedFieldsUpdate(old, basePath)
	allWarns = append(allWarns, warnings...)
	allErrs = append(allErrs, errs...)

	// validate the service override key is valid
	allErrs = append(allErrs, service.ValidateRoutedOverrides(basePath.Child("override").Child("service"), spec.Override.Service)...)

	// When a TopologyRef CR is referenced, fail if a different Namespace is
	// referenced because is not supported
	allErrs = append(allErrs, spec.ValidateTopology(basePath, namespace)...)

	// Validate external Keystone API configuration
	allErrs = append(allErrs, spec.ValidateExternalKeystoneAPI(basePath)...)

	return allWarns, allErrs
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *KeystoneAPI) ValidateDelete() (admission.Warnings, error) {
	keystoneapilog.Info("validate delete", "name", r.Name)

	// TODO(user): fill in your validation logic upon object deletion.
	return nil, nil
}

// ValidateExternalKeystoneAPI validates the external Keystone API configuration
func (spec *KeystoneAPISpecCore) ValidateExternalKeystoneAPI(basePath *field.Path) field.ErrorList {
	var allErrs field.ErrorList

	if !spec.ExternalKeystoneAPI {
		// No validation needed when external Keystone API is not enabled
		return allErrs
	}

	overridePath := basePath.Child("override").Child("service")

	// Both public and internal endpoints must be defined with EndpointURL set
	// This ensures services that depend on both endpoints (like Glance) don't fail
	// when rendering templates
	// Note: We don't check for nil or empty service override here because the
	// hasPublic and hasInternal checks below will catch missing endpoints regardless
	// of whether the map is nil, empty, or contains invalid keys.
	hasPublic := false
	hasInternal := false

	for endpointType, overrideSpec := range spec.Override.Service {
		endpointURLPath := overridePath.Key(string(endpointType)).Child("endpointURL")
		if endpointType == service.EndpointPublic {
			hasPublic = true
			if overrideSpec.EndpointURL == nil || *overrideSpec.EndpointURL == "" {
				allErrs = append(allErrs, field.Required(
					endpointURLPath,
					"external Keystone API requires endpointURL to be set for public endpoint",
				))
			} else {
				// Validate URL format
				parsedURL, err := url.Parse(*overrideSpec.EndpointURL)
				if err != nil {
					allErrs = append(allErrs, field.Invalid(
						endpointURLPath,
						*overrideSpec.EndpointURL,
						fmt.Sprintf("invalid URL format: %v", err),
					))
				} else if parsedURL.Scheme == "" {
					// Require a scheme (http:// or https://)
					allErrs = append(allErrs, field.Invalid(
						endpointURLPath,
						*overrideSpec.EndpointURL,
						"URL must include a scheme (e.g., http:// or https://)",
					))
				}
			}
		}
		if endpointType == service.EndpointInternal {
			hasInternal = true
			if overrideSpec.EndpointURL == nil || *overrideSpec.EndpointURL == "" {
				allErrs = append(allErrs, field.Required(
					endpointURLPath,
					"external Keystone API requires endpointURL to be set for internal endpoint",
				))
			} else {
				// Validate URL format
				parsedURL, err := url.Parse(*overrideSpec.EndpointURL)
				if err != nil {
					allErrs = append(allErrs, field.Invalid(
						endpointURLPath,
						*overrideSpec.EndpointURL,
						fmt.Sprintf("invalid URL format: %v", err),
					))
				} else if parsedURL.Scheme == "" {
					// Require a scheme (http:// or https://)
					allErrs = append(allErrs, field.Invalid(
						endpointURLPath,
						*overrideSpec.EndpointURL,
						"URL must include a scheme (e.g., http:// or https://)",
					))
				}
			}
		}
	}

	if !hasPublic {
		allErrs = append(allErrs, field.Required(
			overridePath,
			fmt.Sprintf("external Keystone API requires %s endpoint to be defined", service.EndpointPublic),
		))
	}

	if !hasInternal {
		allErrs = append(allErrs, field.Required(
			overridePath,
			fmt.Sprintf("external Keystone API requires %s endpoint to be defined", service.EndpointInternal),
		))
	}

	return allErrs
}

// getDeprecatedFields returns the centralized list of deprecated fields for KeystoneAPISpecCore
func (spec *KeystoneAPISpecCore) getDeprecatedFields(old *KeystoneAPISpecCore) []common_webhook.DeprecatedFieldUpdate {
	// Handle NewValue pointer - NotificationsBus can be nil
	var newValue *string
	if spec.NotificationsBus != nil {
		newValue = &spec.NotificationsBus.Cluster
	}

	deprecatedFields := []common_webhook.DeprecatedFieldUpdate{
		{
			DeprecatedFieldName: "rabbitMqClusterName",
			NewFieldPath:        []string{"notificationsBus", "cluster"},
			NewDeprecatedValue:  &spec.RabbitMqClusterName,
			NewValue:            newValue,
		},
	}

	// If old spec is provided (UPDATE operation), add old values
	if old != nil {
		deprecatedFields[0].OldDeprecatedValue = &old.RabbitMqClusterName
	}

	return deprecatedFields
}

// validateDeprecatedFieldsCreate validates deprecated fields during CREATE operations
func (spec *KeystoneAPISpecCore) validateDeprecatedFieldsCreate(basePath *field.Path) ([]string, field.ErrorList) {
	// Get deprecated fields list (without old values for CREATE)
	deprecatedFieldsUpdate := spec.getDeprecatedFields(nil)

	// Convert to DeprecatedField list for CREATE validation
	deprecatedFields := make([]common_webhook.DeprecatedField, len(deprecatedFieldsUpdate))
	for i, df := range deprecatedFieldsUpdate {
		deprecatedFields[i] = common_webhook.DeprecatedField{
			DeprecatedFieldName: df.DeprecatedFieldName,
			NewFieldPath:        df.NewFieldPath,
			DeprecatedValue:     df.NewDeprecatedValue,
			NewValue:            df.NewValue,
		}
	}

	return common_webhook.ValidateDeprecatedFieldsCreate(deprecatedFields, basePath), nil
}

// validateDeprecatedFieldsUpdate validates deprecated fields during UPDATE operations
func (spec *KeystoneAPISpecCore) validateDeprecatedFieldsUpdate(old KeystoneAPISpecCore, basePath *field.Path) ([]string, field.ErrorList) {
	// Get deprecated fields list with old values
	deprecatedFields := spec.getDeprecatedFields(&old)
	return common_webhook.ValidateDeprecatedFieldsUpdate(deprecatedFields, basePath)
}

// SetDefaultRouteAnnotations sets HAProxy timeout values of the route
func (spec *KeystoneAPISpecCore) SetDefaultRouteAnnotations(annotations map[string]string) {
	const haProxyAnno = "haproxy.router.openshift.io/timeout"
	// Use a custom annotation to flag when the operator has set the default HAProxy timeout
	// With the annotation func determines when to overwrite existing HAProxy timeout with the APITimeout
	const keystoneAnno = "api.keystone.openstack.org/timeout"
	valKeystoneAPI, okKeystoneAPI := annotations[keystoneAnno]
	valHAProxy, okHAProxy := annotations[haProxyAnno]
	// Human operator set the HAProxy timeout manually
	if !okKeystoneAPI && okHAProxy {
		return
	}
	// Human operator modified the HAProxy timeout manually without removing the Keystone flag
	if okKeystoneAPI && okHAProxy && valKeystoneAPI != valHAProxy {
		delete(annotations, keystoneAnno)
		return
	}
	timeout := fmt.Sprintf("%ds", spec.APITimeout)
	annotations[keystoneAnno] = timeout
	annotations[haProxyAnno] = timeout
}
